In [3]:
import numpy as np

x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [10]:
%timeit [ j**4 for j in range(1,9) ]

371 ns ± 2.25 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
%timeit [np.arange(1,9)**4]

814 ns ± 1.96 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Array

In [13]:
p = np.array([ [1,2,3,4] , [5,6,7,8]])
print(p)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
zero = np.zeros( (3,4) )
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
ones = np.ones((5,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
print(np.empty(4))

[0. 0. 0. 0.]


In [19]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
print(np.linspace(0,10,num = 5))

[ 0.   2.5  5.   7.5 10. ]


# Random


In [31]:
var = np.random.rand( 3,4 )
print(var)

[[0.86576102 0.55040356 0.13744017 0.65474952]
 [0.6720665  0.88105607 0.84162805 0.68244208]
 [0.3884721  0.76689363 0.21814964 0.08585709]]


In [33]:
var = np.random.randn( 3,4 )
print(var)

[[ 1.41038348 -0.3284894   0.75268559  1.33939807]
 [-1.4290968   0.97464435 -2.02508008 -0.42961306]
 [-1.19826449 -1.24410273  1.77892577  0.15882404]]


In [34]:
var = np.random.ranf(4 )
print(var)

[0.01334622 0.87598744 0.53316234 0.96882954]


In [39]:
var = np.random.randint( 1,20 ,13)
print(var)

[18 11  1 10  1 10  7  5  7 17  4 18  6]


# Datatypes in Numpy

In [44]:
var = np.array([1,2,3,4])
var2 = np.array([1.1,2.1,3.1,4.4])
var3 = np.array(["Neil", "Nitin", "Mukesh"])
print(var , var2 , var3)
print(var.dtype , var2.dtype , var3.dtype)

[1 2 3 4] [1.1 2.1 3.1 4.4] ['Neil' 'Nitin' 'Mukesh']
int64 float64 <U6


In [50]:
var = np.array([1,2,3,4] , dtype="f")
print(var)

[1. 2. 3. 4.]


In [54]:
var = np.array([1,2,3,4])
var2 = var.astype(str)
print(var2)

['1' '2' '3' '4']


# Shape & Resize

In [57]:
var = np.array( [ [1,2], [1,2] ] )
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [58]:
var = np.array( [ 1,2,3,4] , ndmin=5)
print(var)
print()
print(var.shape)

[[[[[1 2 3 4]]]]]

(1, 1, 1, 1, 4)


In [60]:
var = np.array( [ 1,2,3,4] )
var2 = var.reshape(2,2)
print(var.ndim)
print()
print(var2.ndim)

1

2


# Airthmetic operation

In [67]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])

print(a+3)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(b%a)
print(a**b)
print(1/a)



[4 5 6 7]
[ 5  7  9 11]
[-3 -3 -3 -3]
[ 4 10 18 28]
[0.25       0.4        0.5        0.57142857]
[0 1 0 3]
[    1    32   729 16384]
[1.         0.5        0.33333333 0.25      ]


In [69]:
var1 = np.array([ [1,2,3,4], [5,6,7,8] ])
var2 = np.array([ [8,7,6,5], [4,3,2,1] ])

print(var1+var2)
print()
print(1/var1)


[[9 9 9 9]
 [9 9 9 9]]
[[1.         0.5        0.33333333 0.25      ]
 [0.2        0.16666667 0.14285714 0.125     ]]


# Airthmetic Function

In [78]:
a = np.array([1,2,3,4,4,4,2,4,2,5,3])
print(np.min(a))
print(np.max(a))
print(np.argmax(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cumsum(a))
print(np.cumproduct(a))



1
5
9
[1.         1.41421356 1.73205081 2.         2.         2.
 1.41421356 2.         1.41421356 2.23606798 1.73205081]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.7568025  -0.7568025
  0.90929743 -0.7568025   0.90929743 -0.95892427  0.14112001]
[ 1  3  6 10 14 18 20 24 26 31 34]
[    1     2     6    24    96   384   768  3072  6144 30720 92160]


In [83]:
a = np.arange(1,65)
print(a)
print(np.cumproduct(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
[                   1                    2                    6
                   24                  120                  720
                 5040                40320               362880
              3628800             39916800            479001600
           6227020800          87178291200        1307674368000
       20922789888000      355687428096000     6402373705728000
   121645100408832000  2432902008176640000 -4249290049419214848
 -1250660718674968576  8128291617894825984 -7835185981329244160
  7034535277573963776 -1569523520172457984 -5483646897237262336
 -5968160532966932480 -7055958792655077376 -8764578968847253504
  4999213071378415616 -6045878379276664832  3400198294675128320
  4926277576697053184  6399018521010896896  9003737871877668864
  1096907932701818880  4789013295250