In [13]:
import numpy as np 

# Broadcasting

In [14]:
var = np.array([1,2,3])
var2 = np.array([ [1],[2],[3]])

print(var , "\n",var.shape)
print()
print(var2 , "\n",var2.shape)


print()
print(var+var2)


[1 2 3] 
 (3,)

[[1]
 [2]
 [3]] 
 (3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing & Slicing

In [26]:
var = np.array([1,2,3,4,5])
print(var[-3])

var2 = np.array([ [9,8,7] , [6,5,4]])

print("Direct access :", var2[0][2])

for i in var2 : 
    print("i : ", i)
    for j in i : 
        print("j : ", j, end=" ")

3
Direct access : 7
i :  [9 8 7]
j :  9 j :  8 j :  7 i :  [6 5 4]
j :  6 j :  5 j :  4 

In [36]:
var3 = np.array([ [ [1,2], [3,4] ], [ [5,6] , [7,8]] ])
print(var3)
print()

for i in var3 : 
    print("i : ", i)
    for j in i : 
        print("j : ", j)
        print()
        for k in j : 
            print("k : ", k, end=" ")
            print()

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

i :  [[1 2]
 [3 4]]
j :  [1 2]

k :  1 
k :  2 
j :  [3 4]

k :  3 
k :  4 
i :  [[5 6]
 [7 8]]
j :  [5 6]

k :  5 
k :  6 
j :  [7 8]

k :  7 
k :  8 


In [53]:
var = np.array([1,2,3,4,5,6,7,8,9,10])
print(var[0:9:2],"\n")
print(var[9:0:-2], "\n")

var2 = np.array([ [9,8,7,6,5,4,3,2,1] , [6,5,4,3,2,1,9,8,7]])
print(var2[0:,::-1])

[1 3 5 7 9] 

[10  8  6  4  2] 

[[1 2 3 4 5 6 7 8 9]
 [7 8 9 1 2 3 4 5 6]]


In [56]:
for i in np.nditer(var3, flags=["buffered"]):
    print(i*3)

3
6
9
12
15
18
21
24


In [57]:
for i,d in np.ndenumerate(var3 ):
    print(i , d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


# copy vs view

In [64]:
co = var.copy()
vi = var.view()
print(var,"\n",co,"\n",vi,"\n")


[ 1  2  3  4  5  6  7  8  9 10] 
 [ 1  2  3  4  5  6  7  8  9 10] 
 [ 1  2  3  4  5  6  7  8  9 10] 



# join & split function


In [76]:
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
arr = np.concatenate((var,var1))
print(arr)

[1 2 3 4 5 6 7 8]


In [74]:
var = np.array([ [1,2,3,4], [5,6,7,8] ])
var1 = np.array([ [9,10,11,12],[13,14,15,16] ])
arr = np.concatenate((var,var1), axis=0)
arr2 = np.concatenate((var,var1), axis=1)
print(arr,"\n\n",arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

 [[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [79]:
anew = np.stack((var , var1), axis=1) 
print(anew)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [81]:
print(np.hstack((var,var1)))
print()
print(np.vstack((var,var1)))
print()
print(np.dstack((var,var1)))

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# Search ,Sort ,Filter

In [89]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = np.where( arr/2 >= 5 )

print(x)

(array([9]),)


In [92]:
x = np.searchsorted(arr, 4)
print(x)

3


In [93]:
arr1 = np.array([5,3,2,6,7,1,9])
print(np.sort(arr1))

[1 2 3 5 6 7 9]


In [98]:
arr2 = np.array(["a","d","b","f"])
f= [True,False,True,False]

print(arr2[f])

['a' 'b']


# Shuffle , Unique , Resize, Flatten, Ravel Functions

In [102]:
arr = np.array([1,2,4,-1,5])
var = np.random.shuffle(arr1)
print(var)

None


In [107]:
a = np.array([1,1,1,1,2,2,2,3,3,3,4,5,6])
x = np.unique(a, return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6]), array([ 0,  4,  7, 10, 11, 12]), array([4, 3, 3, 1, 1, 1]))


In [110]:
print(np.resize(a,(2,2))) 

[[1 1]
 [1 1]]


# Insert & Delete Functions

In [121]:
a = np.array([1,2,3,4])
np.insert(a,(0,3,4),5)
np.delete(a,2)

array([1, 2, 4])

# Matrix

In [124]:
mat = np.matrix([ [1,2,3],[4,5,6],[7,8,9] ])
mat2 = np.matrix([ [1,2,3],[4,5,6],[7,8,9] ])
print(mat+mat2)
print()
print(mat-mat2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [127]:
print(mat * mat2)
print()
print(mat.dot(mat2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [134]:
a = np.matrix([ [1,2,3] , [4,5,6]])
print(a, "\n")

print(np.transpose(a))
print()

print(np.swapaxes(a, 0 ,1))
print()

print(mat)
print()
print(np.swapaxes(mat,0,1))
print()

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]



In [135]:
print(np.linalg.inv(mat))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [136]:
print(np.linalg.matrix_power(mat,2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [138]:
mat = np.matrix([ [1,2,3],[4,5,6],[1,2,3] ])
print(np.linalg.det(mat))

0.0
